[package]
name = "credit_score"
version = "0.1.0"
edition = "2018"

[dependencies]
cosmwasm-std = { version = "1.0", default-features = false }
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
